--- 
javascripts: 
- application: 
  - prototype
  - application
- effects:
  - effects
  - controls
- addressables:
  - ym4r-gm
  - markerGroup
- iphone:
  - iui  
stylesheets: 
- base: 
  - layout
  - application
  - common_classes
  - forms
- iphone:
  - iui
