--- 
javascripts: 
- application: 
  - application
- autocomplete:
  - jquery.autocomplete.js
- addressables:
  - ym4r-gm
  - markerGroup
stylesheets: 
- arcadefly: 
  - layout
  - application
  - common_classes
  - forms