--- 
javascripts: 
- arcadefly: 
  - application
- autocomplete:
  - jquery_autocomplete
- addressables:
  - ym4r-gm
  - markerGroup
stylesheets: 
- arcadefly: 
  - layout
  - application
  - common_classes
  - forms