class ImportRegions < ActiveRecord::Migration
  def self.up

    us = Country.find_by_alpha_2_code('US')
    ca = Country.find_by_alpha_2_code('CA')

    Region.create(:name=>"Alaska", :abbreviation=>"AK", :country=>us)
    Region.create(:name=>"Alabama", :abbreviation=>"AL", :country=>us)
    Region.create(:name=>"Arkansas", :abbreviation=>"AR", :country=>us)
    Region.create(:name=>"Arizona", :abbreviation=>"AZ", :country=>us)
    Region.create(:name=>"California", :abbreviation=>"CA", :country=>us)
    Region.create(:name=>"Colorado", :abbreviation=>"CO", :country=>us)
    Region.create(:name=>"Connecticut", :abbreviation=>"CT", :country=>us)
    Region.create(:name=>"District of Columbia", :abbreviation=>"DC", :country=>us)
    Region.create(:name=>"Delaware", :abbreviation=>"DE", :country=>us)
    Region.create(:name=>"Florida", :abbreviation=>"FL", :country=>us)
    Region.create(:name=>"Georgia", :abbreviation=>"GA", :country=>us)
    Region.create(:name=>"Hawaii", :abbreviation=>"HI", :country=>us)
    Region.create(:name=>"Iowa", :abbreviation=>"IA", :country=>us)
    Region.create(:name=>"Idaho", :abbreviation=>"ID", :country=>us)
    Region.create(:name=>"Illinois", :abbreviation=>"IL", :country=>us)
    Region.create(:name=>"Indiana", :abbreviation=>"IN", :country=>us)
    Region.create(:name=>"Kansas", :abbreviation=>"KS", :country=>us)
    Region.create(:name=>"Kentucky", :abbreviation=>"KY", :country=>us)
    Region.create(:name=>"Louisiana", :abbreviation=>"LA", :country=>us)
    Region.create(:name=>"Massachusetts", :abbreviation=>"MA", :country=>us)
    Region.create(:name=>"Maryland", :abbreviation=>"MD", :country=>us)
    Region.create(:name=>"Maine", :abbreviation=>"ME", :country=>us)
    Region.create(:name=>"Michigan", :abbreviation=>"MI", :country=>us)
    Region.create(:name=>"Minnesota", :abbreviation=>"MN", :country=>us)
    Region.create(:name=>"Missouri", :abbreviation=>"MO", :country=>us)
    Region.create(:name=>"Mississippi", :abbreviation=>"MS", :country=>us)
    Region.create(:name=>"Montana", :abbreviation=>"MT", :country=>us)
    Region.create(:name=>"North Carolina", :abbreviation=>"NC", :country=>us)
    Region.create(:name=>"North Dakota", :abbreviation=>"ND", :country=>us)
    Region.create(:name=>"Nebraska", :abbreviation=>"NE", :country=>us)
    Region.create(:name=>"New Hampshire", :abbreviation=>"NH", :country=>us)
    Region.create(:name=>"New Jersey", :abbreviation=>"NJ", :country=>us)
    Region.create(:name=>"New Mexico", :abbreviation=>"NM", :country=>us)
    Region.create(:name=>"New York", :abbreviation=>"NY", :country=>us)
    Region.create(:name=>"Nevada", :abbreviation=>"NV", :country=>us)
    Region.create(:name=>"Ohio", :abbreviation=>"OH", :country=>us)
    Region.create(:name=>"Oklahoma", :abbreviation=>"OK", :country=>us)
    Region.create(:name=>"Oregon", :abbreviation=>"OR", :country=>us)
    Region.create(:name=>"Pennsylvania", :abbreviation=>"PA", :country=>us)
    Region.create(:name=>"Rhode Island", :abbreviation=>"RI", :country=>us)
    Region.create(:name=>"South Carolina", :abbreviation=>"SC", :country=>us)
    Region.create(:name=>"Tennessee", :abbreviation=>"TN", :country=>us)
    Region.create(:name=>"Texas", :abbreviation=>"TX", :country=>us)
    Region.create(:name=>"Utah", :abbreviation=>"UT", :country=>us)
    Region.create(:name=>"Virginia", :abbreviation=>"VA", :country=>us)
    Region.create(:name=>"Vermont", :abbreviation=>"VT", :country=>us)
    Region.create(:name=>"Washington", :abbreviation=>"WA", :country=>us)
    Region.create(:name=>"Wisconsin", :abbreviation=>"WI", :country=>us)
    Region.create(:name=>"West Virginia", :abbreviation=>"WV", :country=>us)
    Region.create(:name=>"Wyoming", :abbreviation=>"WY", :country=>us)
    
    Region.create(:name=>"Alberta", :abbreviation=>"AB", :country=>ca)
    Region.create(:name=>"British Columbia", :abbreviation=>"BC", :country=>ca)
    Region.create(:name=>"Manitoba", :abbreviation=>"MB", :country=>ca)
    Region.create(:name=>"Newfoundland and Labrador", :abbreviation=>"NL", :country=>ca)
    Region.create(:name=>"New Brunswick", :abbreviation=>"NB", :country=>ca)
    Region.create(:name=>"Nova Scotia", :abbreviation=>"NS", :country=>ca)
    Region.create(:name=>"Ontario", :abbreviation=>"ON", :country=>ca)
    Region.create(:name=>"Prince Edward Island", :abbreviation=>"PE", :country=>ca)
    Region.create(:name=>"Quebec", :abbreviation=>"QC", :country=>ca)
    Region.create(:name=>"Saskatchewan", :abbreviation=>"SK", :country=>ca)
  end

  def self.down
    execute "TRUNCATE regions"
  end
end